# Generated by Django 4.2.18 on 2025-02-05 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 2, 5, 7, 38, 39, 903373, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
