# Generated by Django 4.2.18 on 2025-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
